version: '3'
services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    volumes:
      - my_mongodb_data:/data/db
    ports:
      - 27017:27017

  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  # Express App
  express-app:
    build: .
    container_name: express-app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  my_mongodb_data:
    driver: local
# docker-compose up -d
