version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017 # make sure you don't have another container running on 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
# docker-compose up -d
